sudo: required 
services:
  - docker

before_install:
  - docker build -t zulfikar2020/react-test -f ./client/Dockerfile.dev .
  
script: 
  - docker run zulfikar2020/react-test npm test -- --coverage

after_success:
  - docker build -t zulfikar2020/multi-client ./client
  - docker build -t zulfikar2020/multi-nginx ./nginx
  - docker build -t zulfikar2020/multi-server ./server
  - docker build -t zulfikar2020/multi-worker ./worker
# log in into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password_stdin
# Take those images and push them into docker hub
  - docker build -t zulfikar2020/multi-client ./client
  - docker build -t zulfikar2020/multi-nginx ./nginx
  - docker build -t zulfikar2020/multi-server ./server
  - docker build -t zulfikar2020/multi-worker ./worker